# SITE SETTINGS
# global meta settings
title:
  en: This is an en website
  nl: Dit is een nl website
description:
  en: This is a great website
  nl: Dit is een prima website
keywords:
  en: shoes
  nl: schoenen
index:
  en: /en/catalog
  nl: /nl/cataloog
baseurl: 
exclude: ['README.md']


# NAVIGATION
# main top navigation
# be sure to add both languages
navi:
  en:
    catalog:
      name: Catalog
      url: /catalog
    promotions:
      name: Promotions
      url: /promotions
    register:
      name: Register
      url: /register
    login:
      name: Login
      url: /login
  nl:
    catalog:
      name: Cataloog
      url: /cataloog
    promotions:
      name: Promoties
      url: /promoties
    register:
      name: Registreren
      url: /registreren
    login:
      name: Inloggen
      url: /inloggen

# NAVIGATION FOOTER
# footer navigation in 3 parts - account, help, about
navi-footer:
  en:
    account:
      login:
        name: Login/Register
        url: /login
    help:
      how:
        name: How to order?
        url: /how-order
      payment:
        name: Payment
        url: /payment
      delivery:
        name: Delivery
        url: /delivery
      privacy:
        name: Privacy policy
        url: /privacy-policy
      terms:
        name: Sales terms
        url: /sales-terms
    about:
      company:
        name: Company
        url: /company
      contact:
        name: Contact us
        url: /contact
  nl:
    account:
      login:
        name: Inloggen/Registreren
        url: /inloggen
    help:
      how:
        name: Hoe bestellen?
        url: /hoe-bestellen
      payment:
        name: Betaling
        url: /betaling
      delivery:
        name: Levering
        url: /levering
      privacy:
        name: Privacy beleid
        url: /privacy-beleid
      terms:
        name: Verkoopsvoorwaarden
        url: /verkoopsvoorwaarden
    about:
      company:
        name: Bedrijf
        url: /bedrijf
      contact:
        name: Contacteer ons
        url: /contacteer-ons

      
# BLOCKS
# render the header and footer block with right language
blocks:
  en:
    header: header-en.html
  nl:
    header: header-nl.html
    
    
